Rogii v2.6.1. Update build scripts
rogii-com/protobuf pull request #2
Opened 2021-09-29 08:15 UTC by Shkarlatov

2021-10-01 13:25 UTC, mr-bit requested changes

2021-10-01 13:25 UTC, mr-bit commented on CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/rogii/npm/Include.cmake)
Unify and add environment.cmake

```
set(
    ROGII_FOLDER_PATH
    "${CMAKE_CURRENT_LIST_DIR}/rogii"
)
include(${ROGII_FOLDER_PATH}/npm/Include.cmake)
include(${ROGII_FOLDER_PATH}/environment.cmake)
```

2021-10-04 10:12 UTC, mr-bit approved these changes

2021-10-05 05:51 UTC, chak3r approved these changes

2021-10-05 11:58 UTC, merged